apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-01-deployment
  labels:
    app: webapp-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-01
  template:
    metadata:
      labels:
        app: webapp-01
    spec:
      containers:
      - name: webapp-01-container
        image: my_image
        ports:
        - containerPort: 8080
