apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-0.1-deployment
  labels:
    app: webapp-0.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-0.1
  template:
    metadata:
      labels:
        app: webapp-0.1
    spec:
      containers:
      - name: webapp-0.1-container
        image: my_image
        ports:
        - containerPort: 8080
